package qualet.irlite.client.forms;

import com.mojang.blaze3d.systems.RenderSystem;
import com.sun.management.ThreadMXBean;
import mchorse.bbs_mod.forms.renderers.FormRenderingContext;
import mchorse.bbs_mod.resources.Link;
import net.minecraft.client.MinecraftClient;
import net.minecraft.util.math.Vec3d;
import org.joml.Matrix3f;
import org.joml.Matrix4f;
import org.joml.Vector3d;
import org.qualet.irl.light.LightRegistry;
import qualet.irlite.client.light.IRLightPositionResolver;
import qualet.irlite.client.light.IRLightPositionResolverBaseline;
import qualet.irlite.client.light.cookie.CookieArray;
import qualet.irlite.client.light.cookie.CookieArrayBaseline;
import qualet.irlite.forms.SpotlightForm;

import java.lang.management.ManagementFactory;
import java.lang.reflect.Field;
import java.util.*;

/** Differential tests of the actual production classes. Boundary fixture sources
 *  are generated by verify-render-cookie.ps1; JOML and LightMath remain real. */
public final class RenderCookieTest
{
    private static long checks;
    private static boolean captureEvents = true;
    private static final List<String> events = new ArrayList<>();
    public static Runnable callback;

    public static void event(String event)
    {
        if (captureEvents) events.add(event);
    }

    public static void main(String[] args) throws Exception
    {
        renderChecks();
        cookieChecks();
        System.out.println("Render/cookie production checks passed: " + checks);
        System.out.println("JVM: " + System.getProperty("java.vm.name") + " " + System.getProperty("java.version"));
        System.out.println("JOML: 1.10.5; compilation target: Java 17; asset/GL and BBS value boundaries are fixtures.");
        benchmark();
    }

    private static void renderChecks()
    {
        FormRenderingContext context = new FormRenderingContext();
        SpotlightForm form = new SpotlightForm();
        SpotlightFormRenderer actual = new SpotlightFormRenderer(form);
        SpotlightFormRendererBaseline baseline = new SpotlightFormRendererBaseline(form);
        Random random = new Random(0x53504f54534cL);
        for (int i = 0; i < 12000; i++)
        {
            Matrix4f local = context.stack.peek().getPositionMatrix();
            local.identity().translate(random.nextFloat()*200-100, random.nextFloat()*200-100,
                    random.nextFloat()*200-100)
                .rotateXYZ(random.nextFloat()*6.28F, random.nextFloat()*6.28F, random.nextFloat()*6.28F)
                .scale(random.nextFloat()*8-4, random.nextFloat()*8-4, random.nextFloat()*8-4);
            RenderSystem.inverse.identity().rotateXYZ(random.nextFloat()*6.28F,
                random.nextFloat()*6.28F, random.nextFloat()*6.28F);
            if (i % 19 == 0) local.scale(0F); // degenerate +Z fallback
            if (i % 23 == 0) local.scale(1e-7F);
            if (i % 29 == 0) local.m03(-0F).m13(0.125F).m23(-0.75F).m33(0.5F);
            if (i % 31 == 0) local.m30(-0F).m31(Float.intBitsToFloat(0x7fc00017)).m32(Float.POSITIVE_INFINITY);
            if (i % 37 == 0) local.m02(Float.NEGATIVE_INFINITY).m22(Float.NaN);
            if (i % 41 == 0) RenderSystem.inverse.identity();
            double magnitude = i % 2 == 0 ? 30_000_000.123456789 : 1e14 + 0.0625;
            MinecraftClient.getInstance().gameRenderer.getCamera().pos = new Vec3d(magnitude, -magnitude, -0.0);

            Vector3d expectedPosition = IRLightPositionResolverBaseline.resolve(context);
            Vector3d actualPosition = IRLightPositionResolver.resolve(context);
            same(expectedPosition.x, actualPosition.x, "legacy API x");
            same(expectedPosition.y, actualPosition.y, "legacy API y");
            same(expectedPosition.z, actualPosition.z, "legacy API z");
            Matrix4f filled = new Matrix4f().zero();
            Vector3d filledPosition = IRLightPositionResolver.resolve(context, filled);
            Matrix4f expectedMatrix = new Matrix4f(RenderSystem.inverse).mul(local);
            for (int c = 0; c < 4; c++) for (int r = 0; r < 4; r++)
                same(expectedMatrix.get(c, r), filled.get(c, r), "caller matrix");
            same(expectedPosition.x, filledPosition.x, "filled API x");
            same(expectedPosition.y, filledPosition.y, "filled API y");
            same(expectedPosition.z, filledPosition.z, "filled API z");

            LightRegistry.lights.clear();
            RenderSystem.reads = 0;
            baseline.registerLight(context);
            check(RenderSystem.reads == 2, "baseline constructs two view products");
            actual.registerLight(context);
            check(RenderSystem.reads == 3, "production constructs one view product");
            try { equalLights(LightRegistry.lights.get(0), LightRegistry.lights.get(1)); }
            catch (AssertionError error) { throw new AssertionError("transform " + i, error); }
        }

        // A real asset callback may recursively render the SAME renderer with a
        // different matrix/camera. Its outer coordinates must survive the call.
        List<double[]> expected = nestedRender(false, context, form, baseline, actual, false);
        List<double[]> observed = nestedRender(true, context, form, baseline, actual, false);
        check(expected.size() == 2 && observed.size() == 2, "nested and outer registration");
        for (int i = 0; i < expected.size(); i++) equalLights(expected.get(i), observed.get(i));
        expected = nestedRender(false, context, form, baseline, actual, true);
        observed = nestedRender(true, context, form, baseline, actual, true);
        for (int i = 0; i < expected.size(); i++) equalLights(expected.get(i), observed.get(i));
        form.cookie.value = null;
        System.out.println("Spot path: 12,000 transforms incl. roll, nonuniform/negative/zero scale, non-affine, NaN/Infinity, signed zero, large camera; nested asset callback and exception PASS.");
    }

    private static List<double[]> nestedRender(boolean optimized, FormRenderingContext context,
        SpotlightForm form, SpotlightFormRendererBaseline baseline, SpotlightFormRenderer actual, boolean failure)
    {
        if (optimized) CookieArray.reload(); else CookieArrayBaseline.reload();
        LightRegistry.lights.clear();
        RenderSystem.inverse.identity().rotateZ(0.9F);
        context.stack.peek().getPositionMatrix().identity().translate(1.25F, -7.5F, 13F).rotateY(0.3F);
        MinecraftClient.getInstance().gameRenderer.getCamera().pos = new Vec3d(30_000_000.125, -4.75, 18.25);
        form.cookie.value = new Link("outer");
        callback = () -> {
            RenderSystem.inverse.identity().rotateX(-0.45F);
            context.stack.peek().getPositionMatrix().identity().translate(-31F, 7F, 0F).scale(2F);
            MinecraftClient.getInstance().gameRenderer.getCamera().pos = new Vec3d(-9000.75, 50.125, 0);
            form.cookie.value = null;
            if (optimized) actual.registerLight(context); else baseline.registerLight(context);
            if (failure) throw new IllegalStateException("asset callback fixture");
        };
        if (optimized) actual.registerLight(context); else baseline.registerLight(context);
        check(callback == null, "asset callback executed");
        return new ArrayList<>(LightRegistry.lights);
    }

    private static void cookieChecks() throws Exception
    {
        bothReload();
        compareResolve(null);
        compareResolve(new Link(""));
        Link mutable = new Link("a");
        compareResolve(mutable);
        mutable.key = "b";
        compareResolve(mutable); // actual key, never Link identity
        for (int i = 0; i < 256; i++) compareResolve(new Link(i % 2 == 0 ? "a" : "b"));
        for (int i = 0; i < 100; i++) compareResolve(new Link("flipbook" + i));
        for (int i = 99; i >= 0; i--) compareResolve(new Link("flipbook" + i));
        for (String key : List.of("missing-asset", "corrupt-image", "upload-fail-image"))
            for (int i = 0; i < 3; i++) compareResolve(new Link(key));
        Random random = new Random(0x434f4f4b4945L);
        for (int i = 0; i < 6000; i++)
        {
            if (i % 307 == 0) bothReload();
            if (i % 193 == 0) bothDelete();
            compareResolve(new Link(switch (random.nextInt(20)) {
                case 0 -> "missing" + random.nextInt(3);
                case 1 -> "corrupt" + random.nextInt(3);
                case 2 -> "upload-fail" + random.nextInt(3);
                default -> "cookie" + random.nextInt(60);
            }));
        }
        // Failed uploads can consume a never-filled layer. Preserve that existing
        // behavior and the resulting full-array eviction trace without repairs.
        bothReload();
        for (int i = 0; i < 32; i++) compareResolve(new Link("upload-fail" + i));
        compareResolve(new Link("full-with-no-residents"));
        bothReload();
        for (int i = 0; i < 32; i++) compareResolve(new Link("overflow" + i));
        setCounter(CookieArray.class, Long.MAX_VALUE - 1);
        setCounter(CookieArrayBaseline.class, Long.MAX_VALUE - 1);
        for (int i = 0; i < 90; i++) compareResolve(new Link("overflow" + i % 40));
        bothReload();
        // Equal-hash String keys force HashMap tree bins. The old two maps and
        // the new single map must still choose the same layer on every eviction.
        for (int i = 0; i < 64; i++) {
            StringBuilder key = new StringBuilder();
            for (int bit = 0; bit < 6; bit++) key.append((i & (1 << bit)) == 0 ? "Aa" : "BB");
            compareResolve(new Link(key.toString()));
        }
        forceTiedStamps(CookieArray.class);
        forceTiedStamps(CookieArrayBaseline.class);
        for (int i = 0; i < 40; i++) compareResolve(new Link("tie" + i));
        bothReload();
        System.out.println("Cookie trace: null/empty/mutable/equal-key links, >128 warm hits, 32+ flipbook, failed read/decode/upload, reload, delete/recreate, empty full pool, stamp overflow PASS.");
    }

    private static void compareResolve(Link link) throws Exception
    {
        events.clear();
        String expected = resolveOutcome(false, link);
        List<String> expectedEvents = new ArrayList<>(events);
        events.clear();
        String actual = resolveOutcome(true, link);
        check(expected.equals(actual), "resolve outcome " + link + ": " + expected + " vs " + actual);
        check(expectedEvents.equals(events), "asset/GL/free trace " + link + ": " + expectedEvents + " vs " + events);
        check(state(CookieArrayBaseline.class).equals(state(CookieArray.class)), "cache state after " + link);
        check(CookieArray.getGlTextureId() == CookieArrayBaseline.getGlTextureId(), "texture lifecycle");
    }

    private static String resolveOutcome(boolean optimized, Link link)
    {
        try { return "layer:" + (optimized ? CookieArray.resolve(link) : CookieArrayBaseline.resolve(link)); }
        catch (RuntimeException e) { return "throw:" + e.getClass().getName(); }
    }

    private static Object get(Object instance, String name) throws Exception
    {
        Field field = instance.getClass().getDeclaredField(name);
        field.setAccessible(true);
        return field.get(instance);
    }

    private static Object instance(Class<?> type) throws Exception
    {
        Field field = type.getDeclaredField("INSTANCE");
        field.setAccessible(true);
        return field.get(null);
    }

    @SuppressWarnings("unchecked")
    private static List<Object> state(Class<?> type) throws Exception
    {
        Object instance = instance(type);
        Map<String, Integer> layers = (Map<String, Integer>) get(instance, "layerByKey");
        Object stamps = get(instance, "lastUse");
        Map<String, Long> liveStamps = new TreeMap<>();
        for (var entry : layers.entrySet())
            liveStamps.put(entry.getKey(), stamps instanceof long[] array ? array[entry.getValue()] :
                ((Map<String, Long>) stamps).get(entry.getKey()));
        return List.of(new TreeMap<>(layers), liveStamps, new TreeSet<>((Set<String>) get(instance, "failed")),
            get(instance, "useCounter"), get(instance, "nextLayer"));
    }

    private static void setCounter(Class<?> type, long value) throws Exception
    {
        Field field = type.getDeclaredField("useCounter");
        field.setAccessible(true);
        field.setLong(instance(type), value);
    }

    @SuppressWarnings("unchecked")
    private static void forceTiedStamps(Class<?> type) throws Exception
    {
        Object stamps = get(instance(type), "lastUse");
        if (stamps instanceof long[] array) Arrays.fill(array, 7L);
        else ((Map<String, Long>) stamps).replaceAll((key, stamp) -> 7L);
        setCounter(type, 7L);
    }

    private static void bothReload()
    {
        events.clear();
        CookieArrayBaseline.reload();
        List<String> expected = new ArrayList<>(events);
        events.clear();
        CookieArray.reload();
        check(expected.equals(events), "reload deletion trace");
    }

    private static void bothDelete()
    {
        events.clear();
        CookieArrayBaseline.delete();
        List<String> expected = new ArrayList<>(events);
        events.clear();
        CookieArray.delete();
        check(expected.equals(events), "delete trace");
    }

    private static void benchmark()
    {
        ThreadMXBean bean = (ThreadMXBean) ManagementFactory.getThreadMXBean();
        if (!bean.isThreadAllocatedMemorySupported()) throw new AssertionError("allocation counters unavailable");
        bean.setThreadAllocatedMemoryEnabled(true);
        LightRegistry.capture = false;
        LightRegistry.sink = 0;
        captureEvents = false;
        CookieArray.reload();
        CookieArrayBaseline.reload();
        Link[] links = new Link[32];
        for (int i = 0; i < links.length; i++) {
            links[i] = new Link("bench" + i);
            CookieArray.resolve(links[i]);
            CookieArrayBaseline.resolve(links[i]);
        }
        FormRenderingContext context = new FormRenderingContext();
        context.stack.peek().getPositionMatrix().rotateXYZ(0.3F, 0.7F, 1.1F).scale(1.3F, 0.7F, -2F);
        RenderSystem.inverse.identity().rotateXYZ(1.2F, 0.4F, -0.6F);
        MinecraftClient.getInstance().gameRenderer.getCamera().pos = new Vec3d(30_000_000.125, 70.75, -900.5);
        SpotlightForm form = new SpotlightForm();
        SpotlightFormRenderer actual = new SpotlightFormRenderer(form);
        SpotlightFormRendererBaseline baseline = new SpotlightFormRendererBaseline(form);
        Runnable oldCookie = () -> { for (int i = 0; i < 300_000; i++) sink += CookieArrayBaseline.resolve(links[i & 31]); };
        Runnable newCookie = () -> { for (int i = 0; i < 300_000; i++) sink += CookieArray.resolve(links[i & 31]); };
        Runnable oldSpot = () -> {
            for (int i = 0; i < 300_000; i++) {
                context.stack.peek().getPositionMatrix().m30((i & 127) * 0.125F);
                baseline.registerLight(context);
            }
        };
        Runnable newSpot = () -> {
            for (int i = 0; i < 300_000; i++) {
                context.stack.peek().getPositionMatrix().m30((i & 127) * 0.125F);
                actual.registerLight(context);
            }
        };
        for (int i = 0; i < 6; i++) { oldCookie.run(); newCookie.run(); oldSpot.run(); newSpot.run(); }
        measure("cookie warm hit (32 keys, Link string generation excluded)", oldCookie, newCookie, bean);
        measure("production spot registration (cookie absent, boundary registry)", oldSpot, newSpot, bean);
        System.out.println("Benchmarks are local CPU/allocation measurements, not Minecraft FPS or game A/B. sink=" + (sink + LightRegistry.sink));
    }

    private static long sink;

    private static void measure(String label, Runnable baseline, Runnable actual, ThreadMXBean bean)
    {
        double[][] nanos = new double[2][9], bytes = new double[2][9];
        for (int round = 0; round < 9; round++) for (int order = 0; order < 2; order++)
        {
            int variant = (order + round) & 1;
            long allocated = bean.getThreadAllocatedBytes(Thread.currentThread().getId());
            long start = System.nanoTime();
            if (variant == 0) baseline.run(); else actual.run();
            nanos[variant][round] = (System.nanoTime() - start) / 300_000.0;
            bytes[variant][round] = (bean.getThreadAllocatedBytes(Thread.currentThread().getId()) - allocated) / 300_000.0;
        }
        for (double[] values : nanos) Arrays.sort(values);
        for (double[] values : bytes) Arrays.sort(values);
        System.out.printf(Locale.ROOT, "%s: old %.3f ns/op, %.3f B/op -> new %.3f ns/op, %.3f B/op (median 9 alternating pairs)%n",
            label, nanos[0][4], bytes[0][4], nanos[1][4], bytes[1][4]);
    }

    private static void equalLights(double[] expected, double[] actual)
    {
        check(expected.length == actual.length, "registry argument count");
        for (int i = 0; i < expected.length; i++) same(expected[i], actual[i], "registry argument " + i);
    }

    private static void same(double expected, double actual, String label)
    {
        // Java does not promise the sign/payload of an arithmetic NaN. JOML can
        // produce different NaN payloads as the same multiply is JIT compiled.
        // Every non-NaN (including signed zero/infinity) must be bit-identical.
        check(Double.doubleToRawLongBits(expected) == Double.doubleToRawLongBits(actual)
                || (Double.isNaN(expected) && Double.isNaN(actual)),
            label + ": " + expected + " (" + Long.toHexString(Double.doubleToRawLongBits(expected))
                + ") vs " + actual + " (" + Long.toHexString(Double.doubleToRawLongBits(actual)) + ")");
    }

    private static void check(boolean condition, String message)
    {
        checks++;
        if (!condition) throw new AssertionError(message);
    }
}
